# Transferbuddy
transferbuddy:
  systemduser: 'transferbuddy'
  # UID must be 1001 or higher
  systemduid: '1001'

# Skopeo Settings
skopeo:
  # Local Destination to sync to
  destination: "/tmp/mirror/containers/"
  # How often to sync images in images.txt in minutes
  frequency: 6
  dryrun: 'True'

# RSYNC - Script uses RSYNC over SSH to sync files
# RSYNC SSH Settings
rsync:
  sshuser: "myuser"
  sshidentity: "~/.ssh/id_rsa"
  sshserver: "192.168.1.6"
  imagedestination: "/srv/mirror/"
  ubuntumirrordestination: "/tmp/mirror/ubuntu/"

# Ubuntu Repo Settings
apt:
  # Local Destination to sync to
  destination: "/tmp/mirror/ubuntu"
  # How often to sync in hours
  frequency: 5
  # Sync on systemd service startup
  onstartup: True
  # Settings for sync and repos. Default Ubuntu 20.04
  basepath: "/var/spool/apt-mirror"
  run_postmirror: '0'
  nthreads: "20"
  tilde: "0"
  repos:
    - 'deb https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal main'
    - 'deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/ focal main'
    - 'deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse'
    #- 'deb http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse'
    #- 'deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse'
  clean: 'http://archive.ubuntu.com/ubuntu'

# CentOS/RockyLinux Repo Settings
yum:
  # Local Destination to sync to
  destination: "/tmp/mirror/centos"
  # How often to sync in hours
  frequency: 5
  # Sync on systemd service startup
  onstartup: True
  repos:
    saltstack-redhat8:
      repoid: 'saltstack-redhat8'
      name: 'Saltstack Redhat 8'
      baseurl: 'https://repo.saltproject.io/py3/redhat/8/x86_64/3004/'
      gpgcheck: '0'
      enabled: '1'
    centos7-base:
      repoid: 'centos-7-base'
      name: 'CentOS 7 Base'
      baseurl: 'http://mirror.centos.org/centos/7/os/x86_64/'
      gpgcheck: '0'
      enabled: '1'
    centos7-updates:
      repoid: 'centos-7-updates'
      name: 'CentOS 7 Updates'
      baseurl: 'http://mirror.centos.org/centos/7/updates/x86_64/'
      gpgcheck: '0'
      enabled: '1'   
    centos7-extras:
      repoid: 'centos-7-extras'
      name: 'CentOS 7 Extras'
      baseurl: 'http://mirror.centos.org/centos/7/extras/x86_64/'
      gpgcheck: '0'
      enabled: '0'    

# Pypi/Bandersnatch Mirror Settings
pypi:
  # Local Destination to sync to
  destination: '/tmp/mirror/pypi'
  frequency: 5
  onstartup: True