FROM ubuntu:20.04
RUN apt-get update -q \
  && \
    apt install -y -qq apt-mirror \
  && \
    touch /var/log/cron.log
{% if mirrorsync.systemduser != 'root' -%}
RUN useradd -u {{ mirrorsync.systemduid }} -ms /bin/bash {{ mirrorsync.systemduser }}
USER {{ mirrorsync.systemduser }}
{% endif -%}
VOLUME ["/var/spool/apt-mirror"]
CMD ["apt-mirror"]
