FROM quay.io/skopeo/stable:v1.10
{% if mirrorsync.systemduser != 'root' -%}
RUN useradd -u {{ mirrorsync.systemduid }} {{ mirrorsync.systemduser }}
USER {{ mirrorsync.systemduser }}
{% endif -%}
VOLUME ["/var/spool/apt-mirror"]