FROM rockylinux:9.0
RUN dnf install -y yum-utils \
  && \
    rm -rf /etc/yum.repos.d/* \
  && \
    mkdir -p /mnt/repos
{% if mirrorsync.systemduser != 'root' -%}
RUN useradd -u {{ mirrorsync.systemduid }} -ms /bin/bash {{ mirrorsync.systemduser }}
USER {{ mirrorsync.systemduser }}
{% endif -%}
VOLUME ["/mnt/repos"]
ENTRYPOINT ["/bin/bash","/opt/rundnf.sh"]
