FROM pypa/bandersnatch
RUN mkdir -p /mnt/repos/
{% if mirrorsync.systemduser != 'root' -%}
RUN useradd -u {{ mirrorsync.systemduid }} -ms /bin/bash {{ mirrorsync.systemduser }}
RUN chown -R {{ mirrorsync.systemduser }} /mnt/repos
RUN chown -R {{ mirrorsync.systemduser }} /bandersnatch
USER {{ mirrorsync.systemduser }}
{% endif -%}
VOLUME ["/mnt/repos"]
CMD ["bandersnatch","-c", "/conf/bandersnatch.conf","mirror"]
